declare 
	@Json varchar(max) = null
	,@NULL varchar(max) = null


set @Json = (

select top 1
	'01' as [identification.suscriberId]
	,'0000000' as [identification.customerNumber]
	,'AP01' as [systemInformation.id]
	,'AP01' as [systemInformation.name]
	,'1.10.20' as [systemInformation.version]
	,'string' as [labelDefinition.wayBillDocument.aditionalInfo]
	,'Documents' as [labelDefinition.wayBillDocument.content]
	,'SPMXA12345' as [labelDefinition.wayBillDocument.costCenter]
	,'null' as [labelDefinition.wayBillDocument.customerShipmentId]
	,'Ref1' as [labelDefinition.wayBillDocument.referenceNumber]
	,'null' as [labelDefinition.wayBillDocument.groupShipmentId]
	,4 as [labelDefinition.itemDescription.parcelId]
	,isnull(CAST(b.Peso as decimal(18,2)),0)as [labelDefinition.itemDescription.weight]
	,ISNULL(CONVERT(int,CEILING(b.Alto)),0) as [labelDefinition.itemDescription.height]
	,ISNULL(CONVERT(int,CEILING(b.Largo)),0) as [labelDefinition.itemDescription.length]
	,ISNULL(CONVERT(int,CEILING(b.Ancho)),0) as [labelDefinition.itemDescription.width]
	--,121.1 as [labelDefinition.itemDescription.merchandises.totalGrossWeight]
	--,'XLU' as[labelDefinition.itemDescription.merchandises.weightUnitCode]
	--,product.Price as[labelDefinition.itemDescription.merchandises.merchandise.merchandiseValue]
	--,'MXN' as[labelDefinition.itemDescription.merchandises.merchandise.currency]
	--,'10131508' as[labelDefinition.itemDescription.merchandises.merchandise.productServiceCode]
	--,c.Product_Quantity as[labelDefinition.itemDescription.merchandises.merchandise.merchandiseQuantity]
	--,'F63' as[labelDefinition.itemDescription.merchandises.merchandise.measurementUnitCode]
	--,'12345678' as[labelDefinition.itemDescription.merchandises.merchandise.tariffFraction]
	--,'ABCDed02-a12A-B34B-c56C-c5abcdef61F2' as[labelDefinition.itemDescription.merchandises.merchandise.UUIDExteriorTrade]
	--,CONVERT(bit,0) as[labelDefinition.itemDescription.merchandises.merchandise.isInternational]
	--,CONVERT(bit,0) as[labelDefinition.itemDescription.merchandises.merchandise.isImport]
	--,CONVERT(bit,0) as[labelDefinition.itemDescription.merchandises.merchandise.isHazardousMaterial]
	--,'M0035' as[labelDefinition.itemDescription.merchandises.merchandise.hazardousMaterialCode]
	--,'4A' as[labelDefinition.itemDescription.merchandises.merchandise.packagingCode]
	,ISNULL(CONVERT(varchar,b.FechaVigenciaGuia),'NoGene') as[labelDefinition.serviceConfiguration.effectiveDate]
	,'Shipment contents' as[labelDefinition.serviceConfiguration.insurance.contentDescription]
	,8 as[labelDefinition.serviceConfiguration.insurance.declaredValue]
	,CONVERT(bit,1) as[labelDefinition.serviceConfiguration.isInsurance]
	,CONVERT(bit,1) as[labelDefinition.serviceConfiguration.isReturnDocument]
	,1 as[labelDefinition.serviceConfiguration.quantityOfLabels]
	,ISNULL(OrigenDestino.Origen_CodigoPosOri,'NoAsig') as[labelDefinition.serviceConfiguration.originZipCodeForRouting]
	,'112' as[labelDefinition.serviceConfiguration.salesOrganization]
	,'70' as[labelDefinition.serviceConfiguration.serviceTypeId]
	,'567' as[labelDefinition.location.destination.deliveryPUDOCode]
	,CONVERT(bit,1) as[labelDefinition.location.destination.homeAddress.address.bUsedCode]
	,'Frente Cementerio' as[labelDefinition.location.destination.homeAddress.address.addressReference]
	,'La Morelos' as[labelDefinition.location.destination.homeAddress.address.betweenRoadName1]
	,'Los Estrada' as[labelDefinition.location.destination.homeAddress.address.betweenRoadName2]
	,'484' as[labelDefinition.location.destination.homeAddress.address.countryCode]
	,'1003' as[labelDefinition.location.destination.homeAddress.address.externalNum]
	,'A' as[labelDefinition.location.destination.homeAddress.address.indoorInformation]
	,'-99.12' as[labelDefinition.location.destination.homeAddress.address.latitude]
	,'19.48' as[labelDefinition.location.destination.homeAddress.address.longitude]
	,'NA999' as[labelDefinition.location.destination.homeAddress.address.nave]
	,'P199' as[labelDefinition.location.destination.homeAddress.address.platform]
	,'Lucio Blanco' as[labelDefinition.location.destination.homeAddress.address.roadName]
	,'001' as[labelDefinition.location.destination.homeAddress.address.roadTypeCode]
	,'Julio Medrano' as[labelDefinition.location.destination.homeAddress.address.settlementName]
	,'001' as[labelDefinition.location.destination.homeAddress.address.settlementTypeCode]
	,'02' as[labelDefinition.location.destination.homeAddress.address.stateCode]
	,'08-019' as[labelDefinition.location.destination.homeAddress.address.townshipCode]
	,OrigenDestino.Origen_CodigoPosOri as[labelDefinition.location.destination.homeAddress.address.zipCode]
	,'7771798529' as[labelDefinition.location.destination.homeAddress.contact.cellPhone]
	,itemDescription.Shipping_Address_First_Name+' '+itemDescription.Shipping_Address_Last_Name as[labelDefinition.location.destination.homeAddress.contact.contactName]
	,itemDescription.Shipping_Address_First_Name+' '+itemDescription.Shipping_Address_Last_Name as[labelDefinition.location.destination.homeAddress.contact.corporateName]
	,'ericka.godezg@mailito.com' as[labelDefinition.location.destination.homeAddress.contact.email]
	,'null' as[labelDefinition.location.destination.homeAddress.contact.phoneExt]
	,'7771011300' as[labelDefinition.location.destination.homeAddress.contact.telephone]
	,CONVERT(bit,0) as[labelDefinition.location.destination.isDeliveryToPUDO]
	,CONVERT(bit,0) as[labelDefinition.location.isDRAAlternative]
	,CONVERT(bit,1) as[labelDefinition.location.origin.address.bUsedCode]
	,'Frente Cementerio' as[labelDefinition.location.origin.address.addressReference]
	,'La Morelos' as[labelDefinition.location.origin.address.betweenRoadName1]
	,'Los Estrada' as[labelDefinition.location.origin.address.betweenRoadName2]
	,'484' as[labelDefinition.location.origin.address.countryCode]
	,'1003' as[labelDefinition.location.origin.address.externalNum]
	,'A' as[labelDefinition.location.origin.address.indoorInformation]
	,'-99.12' as[labelDefinition.location.origin.address.latitude]
	,'19.48' as[labelDefinition.location.origin.address.longitude]
	,'NA999' as[labelDefinition.location.origin.address.nave]
	,'P199' as[labelDefinition.location.origin.address.platform]
	,'Lucio Blanco' as[labelDefinition.location.origin.address.roadName]
	,'001' as[labelDefinition.location.origin.address.roadTypeCode]
	,'Julio Medrano' as[labelDefinition.location.origin.address.settlementName]
	,'001' as[labelDefinition.location.origin.address.settlementTypeCode]
	,'02' as[labelDefinition.location.origin.address.stateCode]
	,'08-019' as[labelDefinition.location.origin.address.townshipCode]
	,OrigenDestino.Origen_CodigoPosOri as[labelDefinition.location.origin.address.zipCode]
	,'5555555544' as[labelDefinition.location.origin.contact.cellPhone]
	,'Julio Medrano' as[labelDefinition.location.origin.contact.contactName]
	,'Distribuidora Intermex, S.A. de C.V.' as[labelDefinition.location.origin.contact.corporateName]
	,'jmedranop@mailito.com' as[labelDefinition.location.origin.contact.email]
	,'2013' as[labelDefinition.location.origin.contact.phoneExt]
	,'5555555555' as[labelDefinition.location.origin.contact.telephone]--
	,'DRFZ' as[labelDefinition.serviceConfiguration.returnDocument.type]
	,'60' as[labelDefinition.serviceConfiguration.returnDocument.serviceId]
	,'Estafeta Mexicana SA de CV' as[labelDefinition.location.DRAAlternative.contact.corporateName]
	,'Luis Godinez' as[labelDefinition.location.DRAAlternative.contact.contactName]
	,'7771798529' as[labelDefinition.location.DRAAlternative.contact.cellPhone]
	,'7771011300' as[labelDefinition.location.DRAAlternative.contact.telephone]
	,'119' as[labelDefinition.location.DRAAlternative.contact.phoneExt]
	,'luis.godezg@estafeta.com' as[labelDefinition.location.DRAAlternative.contact.email]
	,'AOPB010102ROA' as[labelDefinition.location.DRAAlternative.contact.taxPayerCode]
	,CONVERT(bit,1) as[labelDefinition.location.DRAAlternative.address.bUsedCode]
	,'001' as[labelDefinition.location.DRAAlternative.address.roadTypeCode]
	,'string' as[labelDefinition.location.DRAAlternative.address.roadTypeAbbName]
	,'Domingo Diez' as[labelDefinition.location.DRAAlternative.address.roadName]
	,'08-019' as[labelDefinition.location.DRAAlternative.address.townshipCode]
	,'string' as[labelDefinition.location.DRAAlternative.address.townshipName]
	,'001' as[labelDefinition.location.DRAAlternative.address.settlementTypeCode]
	,'string' as[labelDefinition.location.DRAAlternative.address.settlementTypeAbbName]
	,'El Empleado' as[labelDefinition.location.DRAAlternative.address.settlementName]
	,'02' as[labelDefinition.location.DRAAlternative.address.stateCode]
	,'Monterrey' as[labelDefinition.location.DRAAlternative.address.stateAbbName]
	,'62250' as[labelDefinition.location.DRAAlternative.address.zipCode]
	,'484' as[labelDefinition.location.DRAAlternative.address.countryCode]
	,'MEX' as[labelDefinition.location.DRAAlternative.address.countryName]
	,'Junta a Farmacia' as[labelDefinition.location.DRAAlternative.address.addressReference]
	,'La Morelos' as[labelDefinition.location.DRAAlternative.address.betweenRoadName1]
	,'Los Estrada' as[labelDefinition.location.DRAAlternative.address.betweenRoadName2]
	,'-99.12' as[labelDefinition.location.DRAAlternative.address.latitude]
	,'19.48' as[labelDefinition.location.DRAAlternative.address.longitude]
	,'1014' as[labelDefinition.location.DRAAlternative.address.externalNum]
	,'2' as[labelDefinition.location.DRAAlternative.address.indoorInformation]
	,'NA999' as[labelDefinition.location.DRAAlternative.address.nave]
	,'P199' as[labelDefinition.location.DRAAlternative.address.platform]
	,'02' as[labelDefinition.location.DRAAlternative.address.localityCode]
	,'Cozumel' as[labelDefinition.location.DRAAlternative.address.localityName]
	,'notifiedTaxCode' as[labelDefinition.location.notified.notifiedTaxIdCode]
	,'MEX' as[labelDefinition.location.notified.notifiedTaxCountry]
	,'Estafeta Mexicana SA de CV' as[labelDefinition.location.notified.residence.contact.corporateName]
	,'Estafeta Mexicana SA de CV' as[labelDefinition.location.notified.residence.contact.contactName]
	,'7771798529' as[labelDefinition.location.notified.residence.contact.cellPhone]
	,'7771011300' as[labelDefinition.location.notified.residence.contact.telephone]
	,'' as[labelDefinition.location.notified.residence.contact.phoneExt]
	,'ericka.godezg@mailito.com' as[labelDefinition.location.notified.residence.contact.email]
	,'AOPB010102ROA' as[labelDefinition.location.notified.residence.contact.taxPayerCode]
	,CONVERT(bit,1) as[labelDefinition.location.notified.residence.address.bUsedCode]
	,'001' as[labelDefinition.location.notified.residence.address.roadTypeCode]
	,'string' as[labelDefinition.location.notified.residence.address.roadTypeAbbName]
	,'Lucio Blanco' as[labelDefinition.location.notified.residence.address.roadName]
	,'08-019' as[labelDefinition.location.notified.residence.address.townshipCode]
	,'string' as[labelDefinition.location.notified.residence.address.townshipName]
	,'Julio Medrano' as[labelDefinition.location.notified.residence.address.settlementName]
	,'02' as[labelDefinition.location.notified.residence.address.stateCode]
	,OrigenDestino.Origen_EstadoOri as[labelDefinition.location.notified.residence.address.stateAbbName]
	,OrigenDestino.Origen_CodigoPosOri as[labelDefinition.location.notified.residence.address.zipCode]
	,'484' as[labelDefinition.location.notified.residence.address.countryCode]
	,'MEX' as[labelDefinition.location.notified.residence.address.countryName]
	,'Frente Cementerio' as[labelDefinition.location.notified.residence.address.addressReference]
	,'La Morelos' as[labelDefinition.location.notified.residence.address.betweenRoadName1]
	,'Los Estrada' as[labelDefinition.location.notified.residence.address.betweenRoadName2]
	,'-99.12' as[labelDefinition.location.notified.residence.address.latitude]
	,'19.48' as[labelDefinition.location.notified.residence.address.longitude]
	,'A' as[labelDefinition.location.notified.residence.address.indoorInformation]
	,'NA999' as[labelDefinition.location.notified.residence.address.nave]
	,'P199' as[labelDefinition.location.notified.residence.address.platform]
	,'02' as[labelDefinition.location.notified.residence.address.localityCode]
	,OrigenDestino.Origen_Municipio as[labelDefinition.location.notified.residence.address.localityName]
	--itemDescription.Shipping_Address_First_Name+
from Shopify_Orders [itemDescription]
	left outer join Estafeta_Order_Especificaciones b
	on [itemDescription].Order_Id = b.Order_Id
	left outer join Shopify_Order_Products c
	on [itemDescription].Order_Id = c.Order_Id
	left outer join Shopify_Products product
	on c.Product_Id = product.Product_Id
	left outer join Estafeta_Order_OrigenDestino OrigenDestino
	on [itemDescription].Order_Id = OrigenDestino.Order_Id
where 1 = 1
	and b.Estafeta_Guia is null
	and itemDescription.Order_Id = '4632968495348'
FOR JSON PATH
)

select REPLACE(REPLACE(REPLACE(@Json,'"null"','null'),'[',''),']','')  JsonResult